// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Khởi tạo font Inter với biến CSS và hỗ trợ Latin + Vietnamese
const customFont = Inter({
  variable: "--font-custom", // Biến CSS để áp dụng font
  subsets: ["latin", "vietnamese"], // Hỗ trợ Latin và tiếng Việt
  weight: ["400", "500", "700"], // Các trọng lượng font phổ biến
});

// Định nghĩa metadata cho trang
export const metadata: Metadata = {
  title: "Create Next App", // Tiêu đề mặc định
  description: "Generated by create next app", // Mô tả mặc định
};

// Component RootLayout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // Nội dung các trang con
}>) {
  return (
    <html lang="en">
      <body className={`${customFont.variable} antialiased`}>
        {children} {/* Render các trang con */}
      </body>
    </html>
  );
}
